In [211]:
import numpy as np
import pandas as pd

arr = np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [212]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [213]:
print(np.array([[1.5,2.5],[3.5,4.5]]))


[[1.5 2.5]
 [3.5 4.5]]


In [214]:
print(np.linspace(0,1,8))

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [215]:
grid = np.array([[1, 2, 3,4], [5, 6, 7,8], [9, 10, 11,12]])
print(grid)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [216]:
print(grid[1, 2])

7


In [217]:
print(grid[1,:])

[5 6 7 8]


In [218]:
print(grid[:,3])

[ 4  8 12]


In [219]:
print(grid[0:2,2:4])

[[3 4]
 [7 8]]


In [220]:
print(grid[grid>4])

[ 5  6  7  8  9 10 11 12]


In [221]:
scores = np.array([80, 90, 70, 85, 95])
print(scores/10)

[8.  9.  7.  8.5 9.5]


In [222]:
print(scores.mean())

84.0


In [223]:
print(np.median(scores)) 

85.0


In [224]:
print(np.std(scores))

8.602325267042627


In [225]:
print(len(scores[scores>70]))

4


In [226]:
scores[scores<95] = 50
print(scores)

[50 50 50 50 95]


In [227]:
print(scores[::-1])

[95 50 50 50 50]


In [228]:
integers = np.random.randint(1, 100, size=(4, 3))
print(integers)

[[57 21 36]
 [77  6 66]
 [95 98 90]
 [97 94 71]]


In [229]:
print(integers.mean(axis=0))

[81.5  54.75 65.75]


In [230]:
print(integers.argmax(axis=0))

[3 2 2]


In [231]:
print(integers.sum(axis=1))

[114 149 283 262]
