In [2]:
import numpy as np
m = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(m)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [3]:
print(m[:,1])

[20 50 80]


In [ ]:

 
a = np.array([10, 20, 30, 40, 50])
 
print(a[1])
print(a[-1])
print(a[1:4])
print(a[a > 25])
print(a.mean())


20
50
[20 30 40]
[30 40 50]
30.0


In [4]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
 
print(m.shape)
print(m[2, 1])
print(m[:, 2])
print(m[0:2, 0:2])



(3, 3)
8
[3 6 9]
[[1 2]
 [4 5]]


In [5]:
scores = np.array([60, 75, 90, 45, 80])
 
scaled = scores / 100
print(scaled)
print(scores.max())
print(scores.min())
print(scores.sum())
print(round(scores.std(), 2))



[0.6  0.75 0.9  0.45 0.8 ]
90
45
350
15.81


In [6]:
marks = np.array([[80, 90, 70],
                  [60, 75, 85],
                  [95, 55, 65]])
 
print(marks.mean(axis=0))
print(marks.mean(axis=1))
print(marks.max())


[78.33333333 73.33333333 73.33333333]
[80.         73.33333333 71.66666667]
95


In [8]:
print(np.arange(0, 51, 5))

[ 0  5 10 15 20 25 30 35 40 45 50]


In [9]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.random.randint(1,50,8).reshape(4,2))

[[ 4 32]
 [29 48]
 [43  3]
 [41 10]]


In [28]:
data = np.array([[ 5, 12, 38, 47],
                 [61, 23,  9, 84],
                 [15, 72, 55, 31],
                 [48,  6, 90, 17]])
print(data[2, 1]) 


72


In [29]:
print(data[2, :])

[15 72 55 31]


In [19]:
print(data[:,1])

[12 23 72  6]


In [22]:
print(data[data>50])

[61 84 72 55 90]


In [26]:
print(data[-2:, -2:])

[[55 31]
 [90 17]]


In [27]:
data[data < 10] = 0
print(data)

[[ 0 12 38 47]
 [61 23  0 84]
 [15 72 55 31]
 [48  0 90 17]]


In [30]:
marks = np.array([
    [88, 92, 79, 85],   # Student 0
    [95, 87, 91, 78],   # Student 1
    [72, 68, 75, 70],   # Student 2
    [45, 52, 60, 55],   # Student 3
    [91, 88, 84, 93],   # Student 4
    [63, 71, 58, 66],   # Student 5
])
print(marks.shape)

(6, 4)


In [31]:
print(marks.mean(axis=0))

[75.66666667 76.33333333 74.5        74.5       ]


In [32]:
print(marks.mean(axis=1))

[86.   87.75 71.25 53.   89.   64.5 ]


In [42]:
print(marks.mean(axis=1).argmax())

4


In [38]:
print(marks[4,:])

[91 88 84 93]


In [46]:
print(np.where((marks < 60).any(axis=1))[0])

[3 5]


In [47]:
scaled_array = marks / 10
print(scaled_array)

[[8.8 9.2 7.9 8.5]
 [9.5 8.7 9.1 7.8]
 [7.2 6.8 7.5 7. ]
 [4.5 5.2 6.  5.5]
 [9.1 8.8 8.4 9.3]
 [6.3 7.1 5.8 6.6]]


In [52]:
print(np.round(scaled_array, 1))

[[8.8 9.2 7.9 8.5]
 [9.5 8.7 9.1 7.8]
 [7.2 6.8 7.5 7. ]
 [4.5 5.2 6.  5.5]
 [9.1 8.8 8.4 9.3]
 [6.3 7.1 5.8 6.6]]
