In [114]:
import pandas as pd

data = {
    'Player':  ['Rohit', 'Virat', 'Bumrah', 'Jadeja'],
    'Runs':    [9600, 13000, 400, 2800],
    'Active':  [True, True, True, True],
}
df = pd.DataFrame(data)
print(df.shape)
print(df['Runs'][1])
print(df[df['Runs'] > 5000]['Player'].tolist())
print(df.dtypes['Active'])

(4, 3)
13000
['Rohit', 'Virat']
bool


In [115]:
data = {
    'City':    ['Mumbai', 'Delhi', None, 'Pune', 'Delhi'],
    'Temp':    [32.5, 28.0, 31.0, '29.5', 45.0],
    'Season':  ['Summer','Winter','summer','Winter','Summer'],
}
df = pd.DataFrame(data)
df["City"] = df["City"].fillna(df["City"].mode()[0])
print(df)

     City  Temp  Season
0  Mumbai  32.5  Summer
1   Delhi  28.0  Winter
2   Delhi  31.0  summer
3    Pune  29.5  Winter
4   Delhi  45.0  Summer


In [116]:
df["Temp"] = pd.to_numeric(df["Temp"])
print(df)

     City  Temp  Season
0  Mumbai  32.5  Summer
1   Delhi  28.0  Winter
2   Delhi  31.0  summer
3    Pune  29.5  Winter
4   Delhi  45.0  Summer


In [117]:
df["Season"] = df["Season"].str.strip().str.title()
print(df)

     City  Temp  Season
0  Mumbai  32.5  Summer
1   Delhi  28.0  Winter
2   Delhi  31.0  Summer
3    Pune  29.5  Winter
4   Delhi  45.0  Summer


In [118]:
import numpy as np
np.arange(0,21,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [119]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [120]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [121]:
scores = np.array([55, 72, 88, 45, 91, 63])
print(scores[scores>70])

[72 88 91]


In [122]:
products = pd.DataFrame({
    'Product':  ['Pen','Book','Ruler','Bag','Pencil','Eraser'],
    'Price':    [10, 150, 25, 500, 5, 8],
    'Stock':    [200, 50, 80, 30, 300, 150],
    'Category': ['Stationery','Stationery','Stationery','Bag','Stationery','Stationery'],
})
print(products[products["Price"] < 50])

  Product  Price  Stock    Category
0     Pen     10    200  Stationery
2   Ruler     25     80  Stationery
4  Pencil      5    300  Stationery
5  Eraser      8    150  Stationery


In [124]:
products["Value"] = products["Stock"] * products["Price"]
print(products)

  Product  Price  Stock    Category  Value
0     Pen     10    200  Stationery   2000
1    Book    150     50  Stationery   7500
2   Ruler     25     80  Stationery   2000
3     Bag    500     30         Bag  15000
4  Pencil      5    300  Stationery   1500
5  Eraser      8    150  Stationery   1200


In [125]:
print(products.groupby("Category")["Value"].sum())

Category
Bag           15000
Stationery    14200
Name: Value, dtype: int64


In [126]:
products = products.sort_values("Price", ascending=False)
print(products)

  Product  Price  Stock    Category  Value
3     Bag    500     30         Bag  15000
1    Book    150     50  Stationery   7500
2   Ruler     25     80  Stationery   2000
0     Pen     10    200  Stationery   2000
5  Eraser      8    150  Stationery   1200
4  Pencil      5    300  Stationery   1500


In [127]:
products["Expensive"] = products["Price"].apply(lambda x: True if x > 100 else False)
print(products)

  Product  Price  Stock    Category  Value  Expensive
3     Bag    500     30         Bag  15000       True
1    Book    150     50  Stationery   7500       True
2   Ruler     25     80  Stationery   2000      False
0     Pen     10    200  Stationery   2000      False
5  Eraser      8    150  Stationery   1200      False
4  Pencil      5    300  Stationery   1500      False


In [131]:
messy = pd.DataFrame({
    'Student': ['Aryan', 'Priya', None, 'Kabir', 'Aryan'],
    'Score':   [88, 95, 72, None, 88],
    'Grade':   ['B', 'A', 'C', 'B', 'B'],
    'City':    ['Pune', 'delhi', 'PUNE', 'Mumbai', 'Pune'],
})
messy["Student"] = messy["Student"].fillna("Unknown")
print(messy)

   Student  Score Grade    City
0    Aryan   88.0     B    Pune
1    Priya   95.0     A   delhi
2  Unknown   72.0     C    PUNE
3    Kabir    NaN     B  Mumbai
4    Aryan   88.0     B    Pune


In [132]:
messy = messy.drop_duplicates()
print(messy)

   Student  Score Grade    City
0    Aryan   88.0     B    Pune
1    Priya   95.0     A   delhi
2  Unknown   72.0     C    PUNE
3    Kabir    NaN     B  Mumbai


In [133]:
messy["Score"] = messy["Score"].fillna(messy["Score"].mean())
print(messy)

   Student  Score Grade    City
0    Aryan   88.0     B    Pune
1    Priya   95.0     A   delhi
2  Unknown   72.0     C    PUNE
3    Kabir   85.0     B  Mumbai


In [134]:
messy["City"] = messy["City"].str.strip().str.title()
print(messy)

   Student  Score Grade    City
0    Aryan   88.0     B    Pune
1    Priya   95.0     A   Delhi
2  Unknown   72.0     C    Pune
3    Kabir   85.0     B  Mumbai
