In [2]:
import numpy as np

In [3]:
course = np.array([1, 2, 3, 4, 5])

In [4]:
print(course)


[1 2 3 4 5]


In [5]:
print(type(course))

<class 'numpy.ndarray'>


In [6]:
print(course.dtype)

int64


In [10]:
course2 = np.array([
    [6, 7, 8],
    [2,6,9],
    [8,6,1],
])
print(type(course2))

<class 'numpy.ndarray'>


In [8]:
print(course2.dtype)

int64


In [11]:
print(course2.shape)

(3, 3)


In [13]:
print(course2.ndim)

2


In [15]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [17]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [19]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [20]:
np.random.seed(42)
print(np.random.rand(5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [22]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.shape)


(2, 3)


In [23]:
print(a.size)

6


In [24]:
print(a.ndim)

2


In [25]:
print(a.ndim)

2


In [26]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
c = a.reshape(6,1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
flat = a.flatten()
print(flat)

[1 2 3 4 5 6]


In [31]:
a = np.array([1, 2, 3, 4, 5])
print(a[0])

1


In [32]:
print(a[0:3])

[1 2 3]


In [33]:
a = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print(a[0:5])

[1 2 3 4 5]


In [34]:
print(a[4:7])

[5 6 7]


In [35]:
print(a[-3:-1])

[8 9]


In [43]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a[0][0])

1


In [42]:
print(a[0][1])

2
