In [1]:
import numpy as np
a = np.array([1, 2, 3,4,5])
print(a+5)

[ 6  7  8  9 10]


In [2]:
print(a*2)

[ 2  4  6  8 10]


In [3]:
print(a/100)

[0.01 0.02 0.03 0.04 0.05]


In [4]:
print(a**2)

[ 1  4  9 16 25]


In [5]:
maths = np.array([1,2,3])
science = np.array([4,5,6])
print(maths+science)

[5 7 9]


In [6]:
print(maths>science)

[False False False]


In [7]:
print(maths<science)

[ True  True  True]


In [8]:
print(maths==science)

[False False False]


In [9]:
#Aggregation
print(maths.sum())

6


In [10]:
print(maths.mean())

2.0


In [11]:
print(maths.std())

0.816496580927726


In [13]:
print(maths.min())

1


In [14]:
print(maths.max())

3


In [15]:
print(np.median(maths))

2.0


In [17]:
marks = np.array([
    [90, 80, 70],
    [85, 75, 65],
    [95, 85, 75]
])
print(marks.sum(axis=0))

[270 240 210]
